# Generated by Django 4.0.5 on 2022-10-27 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_artiste_age_alter_song_date_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 20, 2, 50, 642320)),
        ),
    ]
