# Generated by Django 4.0.5 on 2022-11-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_alter_lyrics_song_id_alter_song_artiste_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='content',
            field=models.TextField(max_length=20000, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
